G01_6_3: Implemented saving of doctor credentials
shirokov-kirill/Emotional-Support-Capstone pull request #16
Opened 2024-03-22 01:36 UTC by Cabpacob

2024-03-22 12:16 UTC, mrchuvyzgalov requested changes

2024-03-22 12:16 UTC, mrchuvyzgalov commented on app-backend/src/main/resources/db/changelog/2_add_doctor_credentials.yml
> +      id: 1
id: 2

2024-03-22 12:16 UTC, mrchuvyzgalov commented on app-backend/src/main/resources/db/changelog/2_add_doctor_credentials.yml
> +      author: yourName
enter your username here

2024-03-22 12:16 UTC, mrchuvyzgalov commented on app-backend/src/main/resources/db/changelog/2_add_doctor_credentials.yml
> +        - createTable:
Add creating seq_doctor_credentials_id

2024-03-22 12:16 UTC, mrchuvyzgalov commented on app-backend/src/main/kotlin/org/example/appbackend/controller/RegisterDoctorController.kt
> +    fun registerDoctor(@RequestBody dto: RegisterDoctorCredentialsDto) {
Let's bring back DoctorDto because frontend needs to know his id

2024-03-24 20:18 UTC, Cabpacob commented
Fixed

2024-03-26 12:58 UTC, mrchuvyzgalov approved these changes

2024-03-28 13:02 UTC, merged